export const authActionTypes = {
  USER_AUTH_START:'USER_AUTH_START',
  USER_AUTH_SUCCESS:'USER_AUTH_SUCCESS',
  USER_AUTH_FAILURE:'USER_AUTH_FAILURE',
  SET_USER_AUTH:'SET_USER_AUTH',
  SET_CURRENT_USER: 'SET_CURRENT_USER',  
};
